### ISSUE TITLE
Need help with your other repo

### ISSUE THREAD

**Issue by alucard079** [zhouhao27/WOWRibbonView#1]
Sorry, I added issue in this repo. I would like to ask you about the train detector one of your repo.

I'm having a problem in running the `prep.py` I think, I'm having a problem in compilation of it's dependencies would you help me? In your repo of trsin-detector.

**Comment by zhouhao27** [comment]
Are you running with Python 2 or 3? you need to change the code if you're
using python 3.


alucard079 <notifications@github.com> 于 2019年1月7日周一 上午10:44写道：

**Comment by alucard079** [comment]
I'm running python3.

Can you help me on how to compile this with it's dependencies? 

Can I install this with it's dependencies with using virtualenv?

**Comment by alucard079** [comment]
Also can you explain to me what to insert width and height in `crop_plates.py` our size of plate was 390x140 in mm. I'm having a trouble on what size to insert on that `py`. At some point I declare the exact measurement of the character size in `prep.py`

**Comment by alucard079** [comment]
Can you open the issue tab in the train-detector repo? Thank you sir very helpful :(

**Comment by zhouhao27** [comment]
@alucard079 Really sorry. Didn't notice your message. I upload my modified php files here. Please rename it to .py.

[crop_plates.txt](https://github.com/zhouhao27/WOWRibbonView/files/2767532/crop_plates.txt)
[prep.txt](https://github.com/zhouhao27/WOWRibbonView/files/2767533/prep.txt)

**Comment by alucard079** [comment]
Thanks :), Can you explain to me the parameter used in `crop_plates.py` especially the measurement.
Also in the `prep.py` the measurement of width and height what specifically is that? Aside from country which I'm sure of it.

**Comment by zhouhao27** [comment]
Here is what I do:

> python ./crop_plates.py --input_dir vehicle --out_dir sg2 --plate_width=70 --plate_heigh=39

I think height and width should match the one in config file.

**Comment by alucard079** [comment]
Our size of plate was 390x140mm. That arguments is measured in mm? This is exactly what should I input?

Also how do I test the other pretrained detector?
